import { useEffect, useMemo, useRef, useState } from "react";

const CORE_LOOP_CATEGORIES = new Set(["awareness", "action", "reflection", "reset", "growth"]);
const AUTO_GENERATION_ERROR =
  "We couldn't prepare today's plan yet. Open The Loop to try again.";

const NEED_TO_STRUGGLES_MAP = {
  "I can't stop scrolling": ["distraction", "screen addiction", "focus"],
  "I feel lost": ["direction", "clarity", "purpose"],
  "I overthink everything": ["overthinking", "mental noise", "calm"],
  "I have no motivation": ["motivation", "discipline", "action"],
  "I can't sleep": ["sleep", "restlessness", "evening reset"],
  "I feel empty inside": ["emptiness", "meaning", "emotional heaviness"],
  "I keep starting and quitting": ["consistency", "discipline", "follow-through"],
  "I don't know who I am": ["identity", "self-awareness", "purpose"],
  "I feel completely alone": ["loneliness", "connection", "emotional reset"]
};

const getMappedStruggles = (pendingNeed) => {
  if (!pendingNeed || !Array.isArray(pendingNeed.struggles)) return ["clarity", "daily action"];
  const allStruggles = new Set();
  pendingNeed.struggles.forEach(need => {
    const mapped = NEED_TO_STRUGGLES_MAP[need];
    if (mapped) {
      mapped.forEach(s => allStruggles.add(s));
    }
  });
  if (allStruggles.size === 0) return ["clarity", "daily action"];
  return Array.from(allStruggles);
};

const getLocalDate = () => new Date().toLocaleDateString("en-CA");

const getGuardKey = (userId, localDate) =>
  `lifeProject.autoGeneratedLoop.${userId}.${localDate}`;

const normalizeLoopCategory = (value, row = {}) => {
  const subtitle = String(row?.subtitle || "").toLowerCase().replace(/_/g, "-");
  if (subtitle.includes("reflection") || subtitle.includes("journal")) return "reflection";
  if (subtitle.includes("reset") || subtitle.includes("breath") || subtitle.includes("ground")) return "reset";
  if (subtitle.includes("growth") || subtitle.includes("meaning") || subtitle.includes("purpose")) return "growth";
  const category = String(value || "").toLowerCase().replace(/_/g, "-");
  if (category === "meaning") return "growth";
  if (category === "emotional-reset") return "reset";
  return category;
};

const hasTodayCoreTasks = (tasks = []) => {
  const categories = new Set();
  tasks.forEach((task) => {
    const category = normalizeLoopCategory(task?.category, task);
    const isOptional = task?.is_optional === true || task?.is_optional === "true";
    const isCompatCore = isOptional && String(task?.subtitle || "").toLowerCase().includes("practice");
    if (CORE_LOOP_CATEGORIES.has(category) && (!isOptional || isCompatCore)) {
      categories.add(category);
    }
  });
  return Array.from(CORE_LOOP_CATEGORIES).every((category) => categories.has(category));
};

const getSessionStorage = () => {
  if (typeof window === "undefined") return null;
  return window.sessionStorage;
};

export function useEnsureTodayLoopTasks({
  user,
  tasks,
  hasFetched,
  loading,
  error,
  generating,
  generateTasks,
}) {
  const [preparingTodayPlan, setPreparingTodayPlan] = useState(false);
  const [autoGenerationError, setAutoGenerationError] = useState("");
  const localDate = useMemo(getLocalDate, []);
  const existingCoreTasks = hasTodayCoreTasks(tasks);
  const isMounted = useRef(true);

  useEffect(() => {
    return () => {
      isMounted.current = false;
    };
  }, []);

  useEffect(() => {
    if (
      !user?.id ||
      !hasFetched ||
      loading ||
      generating ||
      error ||
      existingCoreTasks ||
      typeof generateTasks !== "function"
    ) {
      return;
    }

    const storage = getSessionStorage();
    const guardKey = getGuardKey(user.id, localDate);

    // Resolve context struggles in priority order:
    // 1. Original onboarding labels from sessionStorage (most specific)
    // 2. User's struggle_tags from auth metadata (persistent across sessions)
    // 3. Mapped keyword fallback from sessionStorage (legacy support)
    let contextStruggles = null;
    if (storage) {
      const pendingRaw = storage.getItem('lifeProject.pendingNeed');
      if (pendingRaw) {
        storage.setItem(`lifeProject.selectedNeed.${user.id}`, pendingRaw);
        storage.removeItem('lifeProject.pendingNeed');
      }

      const selectedRaw = storage.getItem(`lifeProject.selectedNeed.${user.id}`);
      if (selectedRaw) {
        try {
          const parsed = JSON.parse(selectedRaw);
          // Send the original human-readable labels (e.g. "I feel lost")
          // directly — the backend prompt understands them better than keywords.
          if (Array.isArray(parsed.struggles) && parsed.struggles.length > 0) {
            contextStruggles = parsed.struggles.filter(s => typeof s === "string" && s.trim());
          } else {
            contextStruggles = getMappedStruggles(parsed);
          }
        } catch {
          console.warn("[AutoLoop] Could not read saved onboarding context.");
        }
      }
    }

    // Fallback: use struggle_tags already saved in the user's auth metadata
    // (covers returning users and those whose sessionStorage was cleared).
    if (!contextStruggles || contextStruggles.length === 0) {
      const meta = user?.user_metadata ?? {};
      const metaTags =
        meta.struggle_tags ?? meta.struggles ?? meta.onboarding_answers ?? [];
      if (Array.isArray(metaTags) && metaTags.length > 0) {
        contextStruggles = metaTags.filter(s => typeof s === "string" && s.trim());
      }
    }

    if (storage?.getItem(guardKey) === "attempted") {
      return;
    }

    storage?.setItem(guardKey, "attempted");

    const prepareTasks = async () => {
      setPreparingTodayPlan(true);
      setAutoGenerationError("");

      try {
        const generatedTasks = await generateTasks({
          auto: true,
          contextStruggles,
          allowSafeFallback: true,
        });
        if (isMounted.current && !hasTodayCoreTasks(generatedTasks)) {
          // Clear guard so the next page refresh can retry.
          storage?.removeItem(guardKey);
          setAutoGenerationError(AUTO_GENERATION_ERROR);
        }
      } catch {
        console.warn("[AutoLoop] Automatic Loop task preparation failed.");
        storage?.removeItem(guardKey);
        if (isMounted.current) {
          setAutoGenerationError(AUTO_GENERATION_ERROR);
        }
      } finally {
        if (isMounted.current) {
          setPreparingTodayPlan(false);
        }
      }
    };

    prepareTasks();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    error,
    existingCoreTasks,
    generateTasks,
    hasFetched,
    loading,
    localDate,
    user?.id,
  ]);

  return {
    autoGenerationError,
    clearAutoGenerationError: () => setAutoGenerationError(""),
    preparingTodayPlan,
  };
}
