import { useEffect, useMemo, useState } from "react";

const CORE_LOOP_CATEGORIES = new Set(["awareness", "action", "meaning"]);
const AUTO_GENERATION_ERROR =
  "We couldn't prepare today's plan yet. Open The Loop to try again.";

const getLocalDate = () => new Date().toLocaleDateString("en-CA");

const getGuardKey = (userId, localDate) =>
  `lifeProject.autoGeneratedLoop.${userId}.${localDate}`;

const hasTodayCoreTasks = (tasks = []) =>
  tasks.some((task) => {
    const category = String(task?.category || "").toLowerCase();
    const isOptional = task?.is_optional === true || task?.is_optional === "true";
    return CORE_LOOP_CATEGORIES.has(category) && !isOptional;
  });

const getSessionStorage = () => {
  if (typeof window === "undefined") return null;
  return window.sessionStorage;
};

export function useEnsureTodayLoopTasks({
  user,
  tasks,
  hasFetched,
  loading,
  error,
  generating,
  generateTasks,
}) {
  const [preparingTodayPlan, setPreparingTodayPlan] = useState(false);
  const [autoGenerationError, setAutoGenerationError] = useState("");
  const localDate = useMemo(getLocalDate, []);
  const existingCoreTasks = hasTodayCoreTasks(tasks);

  useEffect(() => {
    if (
      !user?.id ||
      !hasFetched ||
      loading ||
      generating ||
      error ||
      existingCoreTasks ||
      typeof generateTasks !== "function"
    ) {
      return;
    }

    const storage = getSessionStorage();
    const guardKey = getGuardKey(user.id, localDate);

    if (storage?.getItem(guardKey) === "attempted") {
      return;
    }

    storage?.setItem(guardKey, "attempted");
    let cancelled = false;

    const prepareTasks = async () => {
      setPreparingTodayPlan(true);
      setAutoGenerationError("");

      try {
        const generatedTasks = await generateTasks({ auto: true });
        if (!cancelled && !hasTodayCoreTasks(generatedTasks)) {
          setAutoGenerationError(AUTO_GENERATION_ERROR);
        }
      } catch (generationError) {
        console.warn("Automatic Loop task preparation failed:", generationError);
        if (!cancelled) {
          setAutoGenerationError(AUTO_GENERATION_ERROR);
        }
      } finally {
        if (!cancelled) {
          setPreparingTodayPlan(false);
        }
      }
    };

    prepareTasks();

    return () => {
      cancelled = true;
    };
  }, [
    error,
    existingCoreTasks,
    generateTasks,
    generating,
    hasFetched,
    loading,
    localDate,
    user?.id,
  ]);

  return {
    autoGenerationError,
    clearAutoGenerationError: () => setAutoGenerationError(""),
    preparingTodayPlan,
  };
}
